---
apiVersion: v1
kind: Service
metadata:
  name: openclaw-gateway
  namespace: openclaw
  labels:
    app: openclaw-gateway
spec:
  type: NodePort
  selector:
    app: openclaw-gateway
  ports:
    - name: http
      port: 18789
      targetPort: http
      nodePort: 30327
